from typing import List, Optional, Union
from pydantic import BaseModel

class MovieModel(BaseModel):
    _id: Optional[str]
    title: str
    link: Optional[Union[str, None]]
    year: Optional[str]
    awards: Optional[str]
    nominations: Optional[str]
    directed_by: Optional[Union[List[str], str]]
    screenplay_by: Optional[Union[List[str], str]]
    based_on: Optional[Union[List[str], str]]
    produced_by: Optional[Union[List[str], str]]
    starring: Optional[List[str]]
    cinematography: Optional[Union[List[str], str]]
    edited_by: Optional[Union[List[str], str]]
    music_by: Optional[Union[List[str], str]]
    productioncompanies: Optional[Union[List[str], str]]
    distributed_by: Optional[Union[List[str], str]]
    release_dates: Optional[List[str]]
    running_time: Optional[Union[List[str], str]]
    countries: Optional[List[str]]
    language: Optional[Union[List[str], str]]
    budget: Optional[Union[List[str], str]]
    box_office: Optional[Union[List[str], str]]
    written_by: Optional[Union[List[str], str]]
    country: Optional[Union[List[str], str]]
    languages: Optional[List[str]]
    revised_hepburn: Optional[str]
    productioncompany: Optional[Union[List[str], str]]
    release_date: Optional[List[str]]
    story_by: Optional[Union[List[str], str]]
    visual_effects_by: Optional[str]
    narrated_by: Optional[Union[List[str], str]]
    animation_by: Optional[Union[List[str], str]]
    spanish: Optional[str]
    french: Optional[str]
    kanji: Optional[str]
    traditional_chinese: Optional[str]
    simplified_chinese: Optional[str]
    hanyu_pinyin: Optional[str]
    producer: Optional[str]
    country_of_origin: Optional[str]
    original_language: Optional[str]
    production_company: Optional[str]
    release: Optional[str]
    italian: Optional[str]
    color_process: Optional[str]
    editor: Optional[str]
    layouts_by: Optional[str]
    backgrounds_by: Optional[str]
    suggested_by: Optional[str]
    adaptation_by: Optional[Union[List[str], str]]